the-control-group/authx

- package.json
- packages/authx/package.json
- packages/authx/schema.sql
- packages/authx/src/graphql/GraphQLAuthorization.ts
- packages/authx/src/index.ts
- packages/authx/src/model/Authority.ts
- packages/authx/src/model/Authorization.ts
- packages/authx/src/model/Client.ts
- packages/authx/src/model/Credential.ts
- packages/authx/src/model/Grant.ts
- packages/authx/src/model/Role.ts
- packages/authx/src/model/User.ts
- packages/authx/src/oauth2.ts
- packages/http-proxy-client/package.json
- packages/http-proxy-resource/package.json
- packages/http-proxy-web/package.json
- packages/interface/package.json
- packages/manager/package.json
- packages/scopes/package.json
- packages/strategy-email/package.json
- packages/strategy-email/src/server/graphql/mutation/authenticateEmail.ts
- packages/strategy-openid/package.json
- packages/strategy-openid/src/server/graphql/mutation/authenticateOpenId.ts
- packages/strategy-password/package.json
- packages/strategy-password/src/server/graphql/mutation/authenticatePassword.ts
- packages/tools/package.json
- packages/tools/src/scripts/bootstrap.ts
- yarn.lock
This fixes #72 by creating "invocations"  when a secret-containing entity is invoked. This PR does **not** address revealing this information via the GraphQL API, which can be addressed as a follow-up feature.
Because this requires a schema change (the addition of new tables) this is a breaking change.
> Record invocations

- packages/authx/src/graphql/GraphQLAuthorization.ts
- packages/authx/src/graphql/mutation/createAuthorizations.ts
- packages/authx/src/graphql/mutation/createClients.ts
- packages/authx/src/graphql/mutation/createGrants.ts
- packages/authx/src/graphql/mutation/createRoles.ts
- packages/authx/src/graphql/mutation/createUsers.ts
- packages/authx/src/model/Authority.ts
- packages/authx/src/model/Authorization.ts
- packages/authx/src/model/Client.ts
- packages/authx/src/model/Credential.ts
- packages/authx/src/model/Grant.ts
- packages/authx/src/model/Role.ts
- packages/authx/src/model/User.ts
- packages/authx/src/oauth2.ts
- packages/strategy-email/src/server/graphql/mutation/createEmailAuthorities.ts
- packages/strategy-email/src/server/graphql/mutation/createEmailCredentials.ts
- packages/strategy-openid/src/server/graphql/mutation/createOpenIdAuthorities.ts
- packages/strategy-openid/src/server/graphql/mutation/createOpenIdCredentials.ts
- packages/strategy-password/src/server/graphql/mutation/createPasswordAuthorities.ts
- packages/strategy-password/src/server/graphql/mutation/createPasswordCredentials.ts
There is no use case for evaluating an authorization's access in
the context of a different authorization, which can only lead to
mistakes.
> Pin context of authorization.access to itself

- packages/authx/src/model/rules/CursorRule.ts
- packages/authx/src/model/rules/IsAccessibleByRule.ts
- packages/authx/src/model/rules/Rule.ts
- packages/authx/src/oauth2.ts
- packages/http-proxy-client/src/index.ts
- packages/http-proxy-resource/src/index.ts
- packages/http-proxy-web/src/index.test.ts
- packages/http-proxy-web/src/index.ts
I went to change the configs for one of the dashboards and realized the proxy makes assumptions about the format of the token. This also adds tests and swaps out "coercing equals (`==`)" for "strict equals (`===`)" in places, just to match the rest of the codebase style.
> Web proxy basic token

- packages/authx/src/graphql/GraphQLAuthorization.ts
- packages/authx/src/graphql/mutation/createAuthorizations.ts
- packages/authx/src/graphql/mutation/createClients.ts
- packages/authx/src/graphql/mutation/createGrants.ts
- packages/authx/src/graphql/mutation/createRoles.ts
- packages/authx/src/graphql/mutation/createUsers.ts
- packages/authx/src/graphql/query/authorizations.ts
- packages/authx/src/graphql/query/clients.ts
- packages/authx/src/graphql/query/credentials.ts
- packages/authx/src/graphql/query/grants.ts
- packages/authx/src/graphql/query/roles.ts
- packages/authx/src/graphql/query/users.ts
- packages/authx/src/model/Authority.ts
- packages/authx/src/model/Authorization.ts
- packages/authx/src/model/Client.ts
- packages/authx/src/model/Credential.ts
- packages/authx/src/model/Grant.ts
- packages/authx/src/model/Role.ts
- packages/authx/src/model/User.ts
- packages/authx/src/model/rules/IsAccessibleByRule.ts
- packages/authx/src/oauth2.ts
- packages/strategy-email/src/server/graphql/mutation/createEmailAuthorities.ts
- packages/strategy-email/src/server/graphql/mutation/createEmailCredentials.ts
- packages/strategy-openid/src/server/graphql/mutation/createOpenIdAuthorities.ts
- packages/strategy-openid/src/server/graphql/mutation/createOpenIdCredentials.ts
- packages/strategy-password/src/server/graphql/mutation/createPasswordAuthorities.ts
- packages/strategy-password/src/server/graphql/mutation/createPasswordCredentials.ts
This implements the feature described in #284 by injecting the scope:
```
authx:v2.authorization..*.{current_client_id}..{current_grant_id}..{current_user_id}:r..*..
```
into the result or an active authorization's `.access` method, and ensuring that this method is used elsewhere.
> Fix #284 - allow authorization introspection

- packages/authx/src/index.ts
- packages/authx/src/oauth2.ts
- packages/http-proxy-web/src/index.ts
- packages/tools/src/lib/fixture/client.ts
- src/superadmin.test.ts
This modifies the authorization code flow to return an access token with scopes limited by those provided in the request.
Fixes #296
> Use narrow scopes in OAuth2 auth code flow

- main.sublime-project
- packages/strategy-saml/src/interface/SamlAuthority.tsx
- packages/strategy-saml/src/server/samlRouter.ts
Currently, logging in with SAML loses parameters stored in the the URL, including those necessary for OAuth from a client. This persists the current URL in a cookie before performing the redirect to the IDP.
Additionally, this changes the cookie names such that they are namespaced by the strategy identifier. This should help avoid conflicts and provide more predictable naming for cookies across strategies/plugins.
> persist url for SAML redirection

- packages/authx/src/model/User.ts
This method is intended to find the active grant between a user and client. However, it incorrectly did not enforce `enabled = TRUE` in its query.
> Fix method to only query enabled grants

- CONTRIBUTING.md
- docker-compose.yaml
- packages/authx/src/graphql/mutation/createAuthorizations.ts
- packages/authx/src/graphql/mutation/createClients.ts
- packages/authx/src/graphql/mutation/createGrants.ts
- packages/authx/src/graphql/mutation/createRoles.ts
- packages/authx/src/graphql/mutation/createUsers.ts
- packages/authx/src/graphql/mutation/updateAuthorizations.ts
- packages/authx/src/graphql/mutation/updateClients.ts
- packages/authx/src/graphql/mutation/updateGrants.ts
- packages/authx/src/graphql/mutation/updateRoles.ts
- packages/authx/src/graphql/mutation/updateUsers.ts
- packages/strategy-email/src/server/graphql/mutation/createEmailAuthorities.ts
- packages/strategy-email/src/server/graphql/mutation/createEmailCredentials.ts
- packages/strategy-email/src/server/graphql/mutation/updateEmailAuthorities.ts
- packages/strategy-email/src/server/graphql/mutation/updateEmailCredentials.ts
- packages/strategy-openid/src/server/graphql/mutation/createOpenIdAuthorities.ts
- packages/strategy-openid/src/server/graphql/mutation/createOpenIdCredentials.ts
- packages/strategy-openid/src/server/graphql/mutation/updateOpenIdAuthorities.ts
- packages/strategy-openid/src/server/graphql/mutation/updateOpenIdCredentials.ts
- packages/strategy-password/src/server/graphql/mutation/createPasswordAuthorities.ts
- packages/strategy-password/src/server/graphql/mutation/createPasswordCredentials.ts
- packages/strategy-password/src/server/graphql/mutation/updatePasswordAuthorities.ts
- packages/strategy-password/src/server/graphql/mutation/updatePasswordCredentials.ts
- packages/strategy-saml/src/server/graphql/mutation/createSamlAuthorities.ts
- packages/strategy-saml/src/server/graphql/mutation/createSamlCredentials.ts
- packages/strategy-saml/src/server/graphql/mutation/updateSamlAuthorities.ts
- packages/strategy-saml/src/server/graphql/mutation/updateSamlCredentials.ts
Make sure that all create/update mutations that accept multiple objects modify them individually and set a fresh executor at the end.
Also fixes a bug in createAuthorizations where multiple subsequent authorizations would be inserted outside a transaction.
> Mutation tweaks

- packages/authx/src/model/Authorization.ts
Because Authorization.access is called at least once for every entity returned in a request, it is a very hot path. Computing scope intersections is a reasonably expensive operation, and the async nature of the backing entities (grant, user, roles) makes this method relatively slow even when those are memoized and db calls can be avoided.
An executor is already the context used for memoization of database calls, and this expands that to include memoization of calls to `Authorization.access`.
> Memoize Authorization.access

- packages/authx/src/graphql/mutation/GraphQLUpdateRoleInput.ts
- packages/authx/src/graphql/mutation/updateRoles.ts
This caused updates of disabled roles over the API to become reenabled when the field was omitted from the request.
> remove default from UpdateRoleInput.enabled

- packages/authx/schema.sql
- packages/authx/src/model/Role.ts
- packages/authx/src/model/User.ts
This fixes #253 by denormalizing replacement_record_id onto role_record_user.
It also adds a _temporary_ flag: when the `AUTHX_ROLE_SCHEMA_MIGRATION` environment variable is set to `true` read queries will use the _old_ queries which to not make use of the new columns. This should allow normal functioning while the schema is being migrated.
The expected migration path is as follows:
1. Deploy the new version with `AUTHX_ROLE_SCHEMA_MIGRATION=true`
2. Add the `role_replacement_record_id` column to `role_record_user`
3. Add indices to `role_record` and `role_record_user`
4. Backfill `role_record_user.role_replacement_record_id` from `role.replacement_record_id`
5. Replace foreign key constraint on `role_record_user`
6. Remove the `AUTHX_ROLE_SCHEMA_MIGRATION` flag
> Fix #253 - Denormalize replacement_record_id onto role_record_user

- packages/authx/src/model/Authorization.ts
- packages/authx/src/model/Grant.ts
- packages/authx/src/model/Role.ts
- packages/authx/src/model/User.ts
- packages/authx/src/util/getAuthorization.ts
- packages/tools/src/lib/fixture/authorization.ts
- packages/tools/src/lib/fixture/grant.ts
- src/disabled.test.ts
- src/graphql/query/authorizations.test.ts
- src/graphql/query/generic.ts
- src/graphql/query/users.test.ts
- src/util.ts
This fixes a few bugs I noticed yesterday around the handling of disabled entities. See the individual commits for more details.
(This would ideally _not_ be squashed when merged, to preserve these distinct commits in history.)
> Normalize access from disabled entities

- packages/authx/schema.sql
This rearranges the SQL file to be more readable, and adds an index condition to take advantage of the newly-denormalized field.
The following can be used to migrate an existing database:
```sql
DROP INDEX role_record_user_user_id_role_record_id_idx;
CREATE INDEX ON authx.role_record_user USING BTREE (user_id, role_record_id) WHERE role_replacement_record_id IS NULL;
```
> Schema optimizations

- packages/authx/src/Config.ts
- packages/authx/src/Context.ts
- packages/authx/src/errors.ts
- packages/authx/src/graphql/GraphQLAuthorization.ts
- packages/authx/src/index.ts
- packages/authx/src/oauth2.ts
- packages/authx/src/util/ratelimiter.ts
- packages/authx/src/util/raterlimiter.test.ts
- packages/strategy-email/src/server/graphql/mutation/authenticateEmail.ts
- packages/strategy-openid/src/server/graphql/mutation/authenticateOpenId.ts
- packages/strategy-password/src/server/graphql/mutation/authenticatePassword.ts
- packages/strategy-saml/src/server/graphql/mutation/authenticateSaml.ts
- src/server.ts
- src/setup.ts
This is a simple implementation that sends 429s if callers do too many invocations of any credential, client, or authorization in a given minute. It uses a simple in-memory per-node rate limiting scheme.
> Rate limiting strategy

- packages/authx/src/util/ratelimiter.ts
- packages/authx/src/util/raterlimiter.test.ts
Currently in some cases it's unclear what key caused a 429 error. This change would make it clear.
> Key added to 429 message

- packages/http-proxy-resource/src/index.ts
This event provides a mechanism for injecting custom headers into the request or response based on other values present in the `meta` object. The driving use-case here is passing the subject and authorization IDs into the protected endpoints for logging and action attribution purposes.
> Add request.proxy event

- .github/workflows/main.yml
- yarn.lock
Yarn 3 changed the name of this command: https://yarnpkg.com/cli/npm/publish/#gatsby-focus-wrapper
> Changed to use new publish command

- packages/authx/package.json
The cause of the current crash loop on dev seems to be that `scopes.js` and `scopes.d.ts` are missing from `3.1.0-alpha.40`. They were in `3.1.0-alpha.35`. I'm not completely sure what's going on, but my guess is that this has something to do with the upgrade from yarn `1` to `3`. Testing with `yarn pack` confirms that yarn is only pushing files in the `files` block, so this should fix the issue.
> Fix missing files issue

- .gitignore
- packages/authx/src/Config.ts
- packages/authx/src/InvocationRecorder.ts
- packages/authx/src/index.ts
- packages/interface/package.json
- src/InvocationRecorder.test.ts
- src/setup.ts
- yarn.lock
Historically, there have been some issues with performance around authorization invocations since each one triggers a write to the database. This change adds in a pluggable "InvocationRecorder" so users can decide to use a different possibly more performant implementation if they want to.
A default EagerInvocationRecorder just follows the current logic, so if users don't add their own implementation, behavior will not change.
> Invocation Recorder

- packages/authx/src/graphql/mutation/createUsers.ts
This message describes an authentication error when it is in fact an authorization error.
> Revise incorrect error message

- lerna.json
- packages/http-proxy-client/src/index.ts
This fixes alerts for prototype pollution vunerabillities. In my assessment the risk here is near-zero, as the keys are trusted configured values and hashes. However, this is still better practice.
> Use null prototype for map values

- .github/workflows/codeql-analysis.yml
This updates the CodsQL workflow to allow direct execution from the `main` branch.
> Allow manual triggering of CodeQL

- packages/http-proxy-web/src/index.test.ts
- packages/http-proxy-web/src/index.ts
This ensures that requests to invalid URL's are safely rejected by the "web" proxy.
> Handle invalid URL in http-proxy-web

- packages/authx/README.md
It looks like the `grant_id` segment was omitted in the resource format description, even though it was present in the matrix. This adds it.
> Fix scope docs
